// <auto-generated />
using System;
using Econolite_API.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Econolite_API.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(EconoliteDbContext))]
    [Migration("20261001083917_AddIntersectionSpeedAndSeeds")]
    partial class AddIntersectionSpeedAndSeeds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Econolite_API.Modules.Audit.Domain.Entities.AuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.ToTable("AuditEntries", (string)null);
                });

            modelBuilder.Entity("Econolite_API.Modules.Identity.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Econolite_API.Modules.Intersections.Domain.Entities.Intersection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("LastDetectorUpdate")
                        .HasColumnType("datetimeoffset");

                    b.Property<double>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("float(9)");

                    b.Property<double>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("float(9)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<int?>("SpeedMph")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("Intersections", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 101,
                            LastDetectorUpdate = new DateTimeOffset(new DateTime(2026, 9, 29, 9, 58, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -7, 0, 0, 0)),
                            Latitude = 33.802100000000003,
                            Longitude = -117.9143,
                            Name = "Harbor Boulevard / Katella Avenue",
                            SpeedMph = 38,
                            Status = "Healthy"
                        },
                        new
                        {
                            Id = 102,
                            LastDetectorUpdate = new DateTimeOffset(new DateTime(2026, 9, 29, 9, 55, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -7, 0, 0, 0)),
                            Latitude = 33.835299999999997,
                            Longitude = -117.9145,
                            Name = "Main Street / Broadway",
                            Status = "Degraded"
                        },
                        new
                        {
                            Id = 103,
                            LastDetectorUpdate = new DateTimeOffset(new DateTime(2026, 9, 29, 9, 59, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -7, 0, 0, 0)),
                            Latitude = 33.836599999999997,
                            Longitude = -117.9417,
                            Name = "Lincoln Avenue / Euclid Street",
                            SpeedMph = 24,
                            Status = "Healthy"
                        },
                        new
                        {
                            Id = 104,
                            LastDetectorUpdate = new DateTimeOffset(new DateTime(2026, 9, 29, 9, 59, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -7, 0, 0, 0)),
                            Latitude = 33.817,
                            Longitude = -117.9417,
                            Name = "Maple Avenue / Seventh Street",
                            SpeedMph = 31,
                            Status = "Healthy"
                        },
                        new
                        {
                            Id = 105,
                            Latitude = 33.810299999999998,
                            Longitude = -117.9221,
                            Name = "Civic Center Drive / First Street",
                            Status = "Offline"
                        },
                        new
                        {
                            Id = 106,
                            LastDetectorUpdate = new DateTimeOffset(new DateTime(2026, 9, 29, 9, 59, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -7, 0, 0, 0)),
                            Latitude = 33.836599999999997,
                            Longitude = -117.9417,
                            Name = "Garden Grove Boulevard / Brookhurst",
                            SpeedMph = 42,
                            Status = "Healthy"
                        },
                        new
                        {
                            Id = 107,
                            LastDetectorUpdate = new DateTimeOffset(new DateTime(2026, 9, 29, 9, 59, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -7, 0, 0, 0)),
                            Latitude = 33.787799999999997,
                            Longitude = -117.8901,
                            Name = "Chapman Avenue / State College Boulevard",
                            SpeedMph = 12,
                            Status = "Degraded"
                        },
                        new
                        {
                            Id = 108,
                            LastDetectorUpdate = new DateTimeOffset(new DateTime(2026, 9, 29, 9, 59, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -7, 0, 0, 0)),
                            Latitude = 33.800899999999999,
                            Longitude = -117.88930000000001,
                            Name = "Orangewood Avenue / Lewis Street",
                            SpeedMph = 35,
                            Status = "Healthy"
                        });
                });

            modelBuilder.Entity("Econolite_API.Modules.TrafficEvents.Domain.Entities.TrafficEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("DetectedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ExternalEventId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("IntersectionId")
                        .HasColumnType("int");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("IntersectionId", "Status");

                    b.HasIndex("SourceSystem", "ExternalEventId")
                        .IsUnique();

                    b.ToTable("TrafficEvents", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e5d99f2c-6825-4d4a-8d3f-b37efc89db01"),
                            DetectedAt = new DateTimeOffset(new DateTime(2026, 9, 29, 9, 55, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -7, 0, 0, 0)),
                            ExternalEventId = "demo-102-001",
                            IntersectionId = 102,
                            Severity = "High",
                            SourceSystem = "DemoDetector",
                            Status = "Active",
                            Type = "Congestion"
                        },
                        new
                        {
                            Id = new Guid("0aef3f85-39c0-4f5c-8ad8-72c7f31f5b02"),
                            DetectedAt = new DateTimeOffset(new DateTime(2026, 9, 29, 9, 51, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -7, 0, 0, 0)),
                            ExternalEventId = "demo-101-001",
                            IntersectionId = 101,
                            Severity = "Medium",
                            SourceSystem = "DemoDetector",
                            Status = "Active",
                            Type = "SlowTraffic"
                        });
                });

            modelBuilder.Entity("Econolite_API.Modules.TrafficEvents.Domain.Entities.TrafficEvent", b =>
                {
                    b.HasOne("Econolite_API.Modules.Intersections.Domain.Entities.Intersection", "Intersection")
                        .WithMany("TrafficEvents")
                        .HasForeignKey("IntersectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Intersection");
                });

            modelBuilder.Entity("Econolite_API.Modules.Intersections.Domain.Entities.Intersection", b =>
                {
                    b.Navigation("TrafficEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
